### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by anbuharry** [TorRient/Video-Summarization-Pytorch#5]
Hai @TorRient 
```

[INFO] CNN processing
VIDIOC_REQBUFS: Inappropriate ioctl for device
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "create_data.py", line 13, in <module>
    gen.generate_dataset()
  File "/content/Video-Summarization-Pytorch/generate_dataset.py", line 120, in generate_dataset
    change_points, n_frame_per_seg = self._get_change_points(video_feat, n_frames,fps)
  File "/content/Video-Summarization-Pytorch/generate_dataset.py", line 53, in _get_change_points
    n = n_frame / fps
ZeroDivisionError: float division by `zero`
```

I got this error could you please help me?

thanks

**Comment by anbuharry** [comment]
This problem occurs only if frames not read 

check the value of the "fps" variable.

Try to give MP4 files you need to change read-only mp4 format or whatever u want. the reason behind this error is data.h5 occurs in dataset folder while reading you videos so u need to edit code like read mp4 files
